config/routes.rb
Rails.application.routes.draw do

  root :to =>"public/homes#top"

  scope module: :public do
    resources :items,only:[:index,:show]
     get 'items/search/:id' => 'items#search',as: 'item_search'
    resources :addresses, only: [:create, :index, :destroy, :edit, :update]
    resources :cart_items, only: [:index, :create, :update, :destroy]
     delete 'cart_items' => 'cart_items#destroy_all', as: 'destroy_all'
    get "orders/complete" => "orders#complete"
    post "orders/confirm" => "orders#confirm"
    resources :orders, only:[:new,:create,:index,:show]
    #resources :customer, only:[:show, :edit, :update]
    # get "customers/unsubscribe" => "public/customers#unsubscribe", as: "unsubscribe"
    # patch "customers/withdraw" => "customers#withdraw", as: "withdraw"
  end

  namespace :admin do
    root "homes#top"
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:show, :index, :edit, :update]
    resources :orders, only: [:show,:update]
    resources :order_details, only: [:update]
    resources :items,only:[:index,:new,:create,:show,:edit,:update]
  end

  get "customers" => "public/customers#show", as: "customer"
  get "customers/:id/edit" => "public/customers#edit", as: "edit_customer"
  patch "customers/:id" => "public/customers#update", as: "update_customer"
  get "customers/:id/unsubscribe" => "public/customers#unsubscribe", as: "unsubscribe"
  patch "customers/:id/withdraw" => "public/customers#withdraw", as: "withdraw"

  get "homes/about"=>"public/homes#about"

  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  validates :postal_code, format: /\A[0-9]+\z/ #郵便番号数字のみ
end

app/models/admin.rb
class Admin < ApplicationRecord
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  has_one_attached :image
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  has_one_attached :image

  validates :item_id, :amount, presence: true
  validates :amount, numericality:{ only_integer: true }

  def sum_of_price
    item.taxin_price * amount
  end

  def subtotal
    item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :cart_items,dependent: :destroy
  has_many :orders,dependent: :destroy
  has_many :addresses,dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         validates :postal_code,length: { minimum: 1, maximum: 7 }
         validates :telephone_number,length: { minimum: 6, maximum: 11 }

  #会員フルネーム
  def full_name
    self.last_name + self.first_name
  end

  #会員フルネーム（カナ）
  def full_name_kana
    self.last_name_kana + self.first_name_kana
  end

  #def active_for_authentication?
    #super && (is_deleted == false)
  #end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items,dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items,dependent: :destroy
  has_many :order_details,dependent: :destroy
  belongs_to :genre
  has_one_attached :image

  def with_tax_price
    (price * 1.1).floor
  end

  def taxin_price
    price*1.1
  end

  #消費税を加えた商品価格
  def add_tax_price
    (self.price * 1.10).round
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details,dependent: :destroy
  enum payment_method: {credit_card: 0, transfer: 1 }
  enum status: {payment_wait: 0,payment_confirm: 1,making: 2,shipping_preparation: 3,shipped: 4}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order
  enum making_status: {making_not: 0,making_wait: 1,making_now: 2,making_comp: 3}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :index
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end


end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items=Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item)
  end

  def show
    @item=Item.find(params[:id])


  end

  def edit
    @item=Item.find(params[:id])
  end

 def update
 @item=Item.find(params[:id])
 @item.update(item_params)
 redirect_to admin_item_path
 end

  private

  def item_params
    params.require(:item).permit(:name,:introduction,:price,:image,:is_active,:genre_id)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def index
    @orders = Order.page(params[:page]).per(10)
  end

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    if @order.status == "payment_confirm"
      @order.order_details.update(making_status: 1)
    end
    redirect_to admin_order_path(@order)
  end

  private

  def order_params
      params.require(:order).permit(:status)
  end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/_index.html.erb
<table class="table table-bordered" style="width: 12rem;">
  <thead>
    <tr>
      <td>ジャンル検索</td>
    </tr>
  </thead>
  <tbody>
    <% genres.each do |genre| %>
    <tr>
     <td>
     <%= link_to item_search_path(genre) do %>
      <%= genre.name %>
     <% end %>
     </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row mt-4">
    <h2>ジャンル編集</h2>
  </div>

  <div class="row mt-3">
    <%= form_with model: @genre, url: admin_genre_path do |f| %>
      <%= f.label "ジャンル名" %>
      <%= f.text_field :name, class: "ml-5" %>
      <%= f.submit '変更を保存', class: "btn btn-success ml-5" %>
    <% end %>
  </div>

</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row mt-4">
    <h2>ジャンル一覧・追加</h2>
  </div>

  <div class="row mt-3">
    <%= form_with model: @genre, url: admin_genres_path, local:true do |f| %>
      <%= f.label "ジャンル名" %>
      <%= f.text_field :name, placeholder: "ジャンル名",class: "ml-5" %>
      <%= f.submit "新規登録", class: "btn btn-success ml-5" %>
    <% end %>
  </div>

  <table class="table col-4 mt-3">
    <thead>
      <tr>
        <th class="table-active text-center">ジャンル</th>
        <th class="table-active"></th>
      </tr>
    </thead>
    <tbody>
      <% @genres.each do |genre| %>
        <tr>
          <td class="align-middle"><%= genre.name %></td>
          <td><%= link_to "編集する", edit_admin_genre_path(genre.id), class: "btn btn-success" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row text-right mt-4">
    <div class="col-sm-4">
     <h3>商品編集</h3>
    </div>
  </div>
 <%= form_with model: @item, url: admin_item_path(@item) do |f|%>
  <div class="row">
   <div class="col-sm-9 offset-3">
    <table class="table-borderless-item">
      <tr>
       <div>
        <p class="my-3">
         <td><%= f.label :商品画像 %></td>
         <td><%=f.file_field :image,acoept: "image/*" %></td>
        </p>
       </div>
      </tr>
      <tr>
        <div class="col-sm-2">
          <p class="my-3">
           <td><%= f.label :商品名 %></td>
           <td><%= f.text_field :name, class:"form-control", placeholder: "商品名" %></td>
          </p>
        </div>
      </tr>
      <tr>
        <div class="col-sm-2">
          <p class="my-3">
          <td><%= f.label :商品説明 %></td>
          <td><%= f.text_area :introduction, class:"form-control", placeholder: "ここに説明文を記述します" %></td>
        </div>
      </tr>
      <tr>
        <div>
          <td><%= f.label :ジャンル %></td>
          <td><%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "--選択してください--" %></td>
        </div>
      </tr>
      <tr>
        <div class="col-sm-2 d-flex flex-row">
          <td><%= f.label :税抜価格 %></td>
          <td><%= f.text_field :price, class:"form-control", placeholder: "1000" %></td>
        </div>
      </tr>
      <tr>
       <div>
          <td><%= f.label :販売ステータス %></td>
          <td><%= f.select :is_active, [["販売中","false"], ["販売不可","true"]], include_blank: "--選択してください--" %></td>
        </div>
      </tr>
     </p>
    </table>
   </div>
  </div>
  <div class="row text-center mb-3">
   <div class="col-sm-12">
     <td><%= f.submit'変更を保存',class: 'btn btn-success col-sm-2' %></td>
   </div>
  </div>
  <% end %>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row text-right mt-4">
    <h4 class="col-sm-2">商品一覧</h4>
    <div class ="col-sm-10">
      <%= link_to new_admin_item_path do %>
       <i class="fas fa-plus-square fa-2x"></i>
      <% end %>

    </div>
  </div>
<div class="row">
 <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th>商品id</th>
        <th>商品名</th>
        <th>税抜価格</th>
        <th>ジャンル</th>
        <th>販売ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @items.each do |item| %>
      <tr>
        <td><%= item.id %></td>
        <td>
          <%=link_to admin_item_path(item.id) do %>
          <%=item.name%>
          <%end%>
          </td>
        <td><%=item.price%></td>
        <td><%=item.genre.name%></td>
         <td><% if item.is_active == false %>
              <p class="color text-success", style="margin:0">販売中</p>
              <% else %>
              <p class="color text-secondary", style="margin:0">販売停止中</p>
             <% end %></td>
      </tr>
      <% end %>
    </tbody>
 </table>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row text-right mt-4">
    <div class="col-sm-4">

      <h3>商品新規登録</h3>
    </div>
  </div>
 <%= form_with model: @item, url: admin_items_path do |f|%>
   <div class="row">
    <div class="col-sm-9 offset-3">
       <table class="table-borderless-item">
         <tr>
          <div>
            <p class="my-3">
             <td><%= f.label :商品画像 %></td>
             <td><%=f.file_field :image,acoept: "image/*" %></td>
            </p>
          </div>
         </tr>
         <tr>
          <div class="col-sm-2">
            <p class="my-3">
             <td><%= f.label :商品名 %></td>
             <td><%= f.text_field :name, class:"form-control", placeholder: "商品名" %></td>
            </p>
          </div>
         </tr>
         <tr>
          <div class="col-sm-2">
            <p class="my-3">
            <td><%= f.label :商品説明 %></td>
            <td><%= f.text_area :introduction, class:"form-control", placeholder: "ここに説明文を記述します" %></td>
          </div>
         </tr>
         <tr>
          <div>
            <td><%= f.label :ジャンル %></td>
            <td><%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "--選択してください--" %></td>
          </div>
         </tr>
         <tr>
          <div class="col-sm-2 d-flex flex-row">
            <td><%= f.label :税抜価格 %></td>
            <td><%= f.text_field :price, class:"form-control", placeholder: "1000" %></td>
          </div>
         </tr>
         <tr>
          <div>
            <td><%= f.label :販売ステータス %></td>
            <td><%= f.select :is_active, [["販売中","false"], ["販売不可","true"]], include_blank: "--選択してください--" %></td>
          </div>
         </tr>
        </p>
       </table>
    </div>
   </div>
     <div class="row text-center mb-3">
      <div class="col-sm-12">
        <td><%= f.submit "新規登録" ,class: 'btn btn-success col-sm-2' %></td>
      </div>
    </div>

 <% end %>
</div>

app/views/admin/items/show.html.erb
<div class="container">
 <div class="row my-5">
  <div class="col-sm-5 offset-1">
    <h3>商品詳細</h3>
    <%=image_tag @item.image, size: '300x200'%>
  </div>
  <div class="col-sm-6">
   <table class="table table-borderless">
    <tbody>
     <tr>
       <td>商品名</td>
       <td><%= @item.name %></td>
     </tr>
     <tr>
       <td>商品説明</td>
       <td><%= @item.introduction %></td>
     </tr>
     <tr>
       <td>ジャンル</td>
       <td><%= @item.genre.name %></td>
     </tr>
     <tr>
       <td>税込価格(税抜価格)</td>
       <td><%= @item.with_tax_price.to_s(:delimited) %>(<%=@item.price%>)円</td>
     </tr>
     <tr>
       <td>販売ステータス</td>
       <td><% if @item.is_active == false %>
             販売中
             <% else %>
             販売停止中
           <% end %></td>
     </tr>
    </tbody>
   </table>
  </div>
 </div>
 <div class="row mb-3">
  <div class="col-sm-12">
    <div class="text-center">
     <%= link_to "編集する",edit_admin_item_path(@item.id),class: 'btn btn-success col-sm-2' %>
   </div>
  </div>
 </div>
</div>

app/views/admin/orders/index.html.erb
<div class="container">
  <div class="row mt-4">
    <h2>注文履歴一覧</h2>
  </div>

  <table class="table mt-3">
    <thead>
      <tr>
        <th class="table-active">購入日時</th>
        <th class="table-active">購入者</th>
        <th class="table-active">注文個数</th>
        <th class="table-active">注文ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td><u><%= link_to order.created_at.strftime('%Y/%m/%d %H:%M:%S'), admin_order_path(order.id) %></u></td>
          <td><%= order.customer.full_name %></td>
          <td><%= order.order_details.sum(:amount) %></td>
          <td><%= order.status_i18n %></td> <!-- _i18nでenumを日本語化 -->
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="row justify-content-center">
    <%= paginate @orders %>
  </div>

</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row mt-4">
    <h2>注文履歴詳細</h2>
  </div>

  <div class="row mt-3">
    <div class="col-2"><strong>購入者</strong></div>
    <div class="col-3"><%= @order.customer.full_name %></div>
  </div>
  <div class="row mt-2">
    <div class="col-2"><strong>注文日</strong></div>
    <div class="col-3"><%= @order.created_at.strftime('%Y/%m/%d') %></div>
  </div>
  <div class="row mt-2">
    <div class="col-2"><strong>配送先</strong></div>
    <div class="col-3">
      <%= @order.postal_code %> <%= @order.address %><br>
      <%= @order.name %>
    </div>
  </div>
  <div class="row mt-2">
    <div class="col-2"><strong>支払方法</strong></div>
    <div class="col-3"><%= @order.payment_method_i18n %></div>
  </div>
  <div class="row mt-2">
    <div class="col-2"><strong>注文ステータス</strong></div>
    <div class="col-3">
      <%= form_with model: @order, url: admin_order_path(@order), method: :patch, local: true do |f| %>
        <%= f.select :status, Order.statuses.keys.map {|k| [I18n.t("enums.order.status.#{k}"), k]} %>
        <%= f.submit "更新", class: "btn btn-success ml-4"%>
      <% end %>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col-8">
      <table class="table">
        <thead>
          <tr>
            <th class="table-active">商品名</th>
            <th class="table-active">単価（税込）</th>
            <th class="table-active">数量</th>
            <th class="table-active">小計</th>
            <th class="table-active">製作ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @order_details.each do |order_detail| %>
            <tr>
              <td><%= order_detail.item.name %></td>
              <td><%= order_detail.price %></td>
              <td><%= order_detail.amount %></td>
              <td><%= order_detail.price*order_detail.amount%></td>
              <td>
                <%= form_with model: order_detail, url: admin_order_detail_path(order_detail), method: :patch, local: true do |f| %>
                  <%= f.select :making_status, OrderDetail.making_statuses.keys.map {|k| [I18n.t("enums.order_detail.making_status.#{k}"), k]} %>
                  <%= f.submit "更新", class: "btn btn-success ml-4"%>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="col-3 d-flex align-items-end">
      <table class="table table-borderless">
        <tr>
          <td><strong>商品合計</strong></td>
          <td><%= @order.total_payment-800 %></td>
        </tr>
        <tr>
          <td><strong>配送料金</strong></td>
          <td><%= "800" %></td>
        </tr>
        <tr>
          <td><strong>請求金額合計</strong></td>
          <td><strong><%= @order.total_payment.to_s(:delimited, delimiter: ',') %></strong></td>
        </tr>
      </table>
    </div>
  </div>

</div>