config/routes.rb
Rails.application.routes.draw do

  root :to =>"public/homes#top"

  scope module: :public do
    resources :items,only:[:index,:show]
     get 'items/search/:id' => 'items#search',as: 'item_search'
    resources :addresses, only: [:create, :index, :destroy, :edit, :update]
    resources :cart_items, only: [:index, :create, :update, :destroy]
     delete 'cart_items' => 'cart_items#destroy_all', as: 'destroy_all'
    get "orders/complete" => "orders#complete"
    post "orders/confirm" => "orders#confirm"
    resources :orders, only:[:new,:create,:index,:show]
    #resources :customer, only:[:show, :edit, :update]
    # get "customers/unsubscribe" => "public/customers#unsubscribe", as: "unsubscribe"
    # patch "customers/withdraw" => "customers#withdraw", as: "withdraw"
  end

  namespace :admin do
    root "homes#top"
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:show, :index, :edit, :update]
    resources :orders, only: [:show,:update]
    resources :order_details, only: [:update]
    resources :items,only:[:index,:new,:create,:show,:edit,:update]
  end

  get "customers" => "public/customers#show", as: "customer"
  get "customers/:id/edit" => "public/customers#edit", as: "edit_customer"
  patch "customers/:id" => "public/customers#update", as: "update_customer"
  get "customers/:id/unsubscribe" => "public/customers#unsubscribe", as: "unsubscribe"
  patch "customers/:id/withdraw" => "public/customers#withdraw", as: "withdraw"

  get "homes/about"=>"public/homes#about"

  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  validates :postal_code, format: /\A[0-9]+\z/ #郵便番号数字のみ
end

app/models/admin.rb
class Admin < ApplicationRecord
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  has_one_attached :image
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  has_one_attached :image

  validates :item_id, :amount, presence: true
  validates :amount, numericality:{ only_integer: true }

  def sum_of_price
    item.taxin_price * amount
  end

  def subtotal
    item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :cart_items,dependent: :destroy
  has_many :orders,dependent: :destroy
  has_many :addresses,dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         validates :postal_code,length: { minimum: 1, maximum: 7 }
         validates :telephone_number,length: { minimum: 6, maximum: 11 }

  #会員フルネーム
  def full_name
    self.last_name + self.first_name
  end

  #会員フルネーム（カナ）
  def full_name_kana
    self.last_name_kana + self.first_name_kana
  end

  #def active_for_authentication?
    #super && (is_deleted == false)
  #end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items,dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items,dependent: :destroy
  has_many :order_details,dependent: :destroy
  belongs_to :genre
  has_one_attached :image

  def with_tax_price
    (price * 1.1).floor
  end

  def taxin_price
    price*1.1
  end

  #消費税を加えた商品価格
  def add_tax_price
    (self.price * 1.10).round
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details,dependent: :destroy
  enum payment_method: {credit_card: 0, transfer: 1 }
  enum status: {payment_wait: 0,payment_confirm: 1,making: 2,shipping_preparation: 3,shipped: 4}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order
  enum making_status: {making_not: 0,making_wait: 1,making_now: 2,making_comp: 3}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end


end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items=Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item)
  end

  def show
    @item=Item.find(params[:id])


  end

  def edit
    @item=Item.find(params[:id])
  end

 def update
 @item=Item.find(params[:id])
 @item.update(item_params)
 redirect_to admin_item_path
 end

  private

  def item_params
    params.require(:item).permit(:name,:introduction,:price,:image,:is_active,:genre_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />

<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
    <div class='row'>
      <div class='mx-auto'>
        <p>NAGANO CAKE</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color:#bc8f8f;">
    <div class="container">
      <nav class="navbar-brand navbar-left header-logo">
        <%= link_to image_tag("logo1.png", size: "70x50"), root_path, class: "header-button btn text-light" %>
      </nav>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="nav navbar-nav ml-auto">
          <!-- 顧客がログインしている時 -->
          <% if customer_signed_in? %>
            <p>ようこそ、<%= current_customer.last_name %>さん！</p>
            <li><%= link_to "マイページ", customer_path, class: "header-button btn text-light" %></li>
            <li><%= link_to "商品一覧",  items_path, class: "header-button btn text-light" %></li>
            <li><%= link_to "カート", cart_items_path, class: "header-button btn text-light" %></li>
            <li><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "header-button btn text-light" %></li>

          <!-- 管理者がログインしている時 -->
          <% elsif admin_signed_in? %>
            <li><%= link_to "商品一覧", admin_items_path, class: "header-button btn text-light" %></li>
            <li><%= link_to "会員一覧", admin_customers_path, class: "header-button btn text-light" %></li>
            <li><%= link_to "注文履歴一覧", admin_root_path, class: "header-button btn text-light" %></li>
            <li><%= link_to "ジャンル一覧", admin_genres_path, class: "header-button btn text-light" %></li>
            <li><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "header-button btn text-light" %></li>

          <!-- ログインしていない時 -->
          <% else %>
            <li><%= link_to "About", homes_about_path, class: "header-button btn text-light" %></li>
            <li><%= link_to "商品一覧", items_path, class: "header-button btn text-light" %></li>
            <li><%= link_to "新規登録", new_customer_registration_path, class: "header-button btn text-light" %></li>
            <li><%= link_to "ログイン", new_customer_session_path, class: "header-button btn text-light" %></li>
            <li><%= link_to "管理者ログイン", new_admin_session_path, class: "header-button btn text-light" %></li>
          <% end %>
        </ul>

        <!-- 検索機能 -->
        <form class="d-flex">
          <input class="ml-2 form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-light ml-2" type="submit">
            <i class="fas fa-search"></i>
          </button>
        </form>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Naganocake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/header' %>
    </header>
    <main>
    <%= yield %>
    </main>
    <footer>
      <%= render 'layouts/footer' %>
    </footer>
  </body>

</html>